---
- hosts: all
  become: yes

  tasks:
          - name: install tomcat
            apt:
                    name: tomcat
                    state: present

          - name: install tomcat
            apt: name=tomcat state=present
