---
- hosts: all
  become: yes
  gather_facts: false

  tasks:
          - name: install nginx by calling handler
            shell: apt update
            notify:
                    - install nginx
                    - start nginx



  handlers:

          - name: install nginx
            apt: name=nginx state=present

          - name: start nginx
            service: name=nginx state=started enabled=yes
