---
- hosts: RHELClient
  become: yes

  tasks:
          - name: stop apache
            service: name=httpd state=stopped enabled=no

          - name: remove apache
            yum: name=httpd state=absent
