---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
        - name: install nginx
          apt: name=nginx state=present
          

        - name: staer the service of nginx
          service: name=nginx state=started enabled=yes

        - name: restart of nginx
          service: name=nginx state=restarted enabled=yes

        - name: create logs directory
          shell: mkdir testdir1
